server {
    listen 80;
    server_name stapp02;

    return 301 https$host$request_uri;
}

server {
    listen 443 ssl;
    server_name stapp02;

    root usrsharenginxhtml;
    index index.html;

    ssl_certificate etcnginxsslnautilus.crt;
    ssl_certificate_key etcnginxsslnautilus.key;

    location  {
        try_files $uri $uri =404;
    }
}